{"name": "test_add[get_datas83]", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <pratice_lesson4.pratice.testing.test_calc_new.TestCalculator object at 0x0000023D656CA670>\nget_calc = <pratice_lesson4.pratice.demo.calc.Calculator object at 0x0000023D656052E0>, get_datas = [999999999, 1, 1000000000]\n\n    @allure.story(\"计算器的加法测试\")\n    def test_add(self,get_calc,get_datas):\n        #调用add方法\n        with allure.step(\"从计算器的加方法中得到加过的值\"):\n            result = get_calc.add(get_datas[0],get_datas[1])\n        #假设最大能输入999999999\n        if result>=1000000000:\n            print(\"超出最大数值999999999，不允许输出\")\n>           assert False\nE           assert False\n\ntest_calc_new.py:48: AssertionError"}, "steps": [{"name": "从计算器的加方法中得到加过的值", "status": "passed", "start": 1612262377318, "stop": 1612262377318}], "parameters": [{"name": "get_datas", "value": "[999999999, 1, 1000000000]"}], "start": 1612262377318, "stop": 1612262377318, "uuid": "54d91135-a214-4f9e-bb32-196e678cf6d0", "historyId": "3f222a7f681d18f347ac2b81ae768b71", "testCaseId": "3d63d6b6e535a2d30dc56b2e66da2d0a", "fullName": "test_calc_new.TestCalculator#test_add", "labels": [{"name": "feature", "value": "测试计算器"}, {"name": "story", "value": "计算器的加法测试"}, {"name": "suite", "value": "test_calc_new"}, {"name": "subSuite", "value": "TestCalculator"}, {"name": "host", "value": "Naraku15"}, {"name": "thread", "value": "18708-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_calc_new"}]}